---
version: "3"
name: orchestra

services:

    postgres:
        image: postgres:latest
        ports:
            - 5432:5432
        restart: always
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: postgrespw
            
    pgadmin:
        image: dpage/pgadmin4:latest
        depends_on:
            - postgres
        ports:
            - 5050:80
        restart: always
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
            PGADMIN_DEFAULT_PASSWORD: postgres

volumes:
    postgres-data:
    pgadmin-data:
